apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: inference-services-mlops-team
  namespace: ai-delivery-portal
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/cuongct924/AI-delivery-portal.git
        branch: main
        includePaths:
          - infra/environments/dev/inference-services/mlops-team
